### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by mattjohnsonpint** [vvpvvp/momentjs#2]
Hello,

I'm a maintainer of the [moment.js](http://momentjs.com) project.  We are starting to get bug reports because people are confusing your library with ours.  Could you kindly rename your project to something else?

In particular, the npm package name [`momentjs`](https://www.npmjs.com/package/momentjs) is too similar to our [`moment`](https://www.npmjs.com/package/moment) package name, and thus people that want to install moment.js, expecting the full API of moment.js, end up installing your package instead.   Please remove/rename your npm package to prevent this confusion.

Also, since it appears that parts of your code are taken from the moment.js code, then please give appropriate attribution in your readme and license file.  The MIT license allows for modification, but requires the original copyright notice to be retained.  It's sufficient to state something like:

```
Parts of this code are from the moment.js project, http://momentjs.com
Copyright (c) 2011-2016 Tim Wood, Iskren Chernev, Moment.js contributors
```

Thanks.

**Comment by vvpvvp** [comment]
I am so sorry, I didn't realized there is such a problem.
I found that if I rename the momentjs package, that will cause a lot of problems.
 Our team use this package, and we deployed it in many place.
I could give a declaration about the difference in my readme,  on the top of the page, and in English.
In the end, my code just wrote by myself, it has no relationship with the moment.js code, I will not give the attribution in my readme and license file.
Thanks.

**Comment by mattjohnsonpint** [comment]
Sorry, but this isn't really a good solution for either of us.  Your readme, logo, website, api, etc. are very clearly set up to compete with moment.js.  That there's competition is fine - there are lots of good date libraries out there.  That you are calling it the exact same thing as ours is just not very respectful to the JavaScript community.  Anyone who actually wants your library might choose ours instead, and vice-versa.

Please understand that moment.js has over 5 MILLION downloads per month on npm, has over 27,000 stars and 3,900 forks on GitHub, and is used in many thousands of high-profile public and private web applications, etc.  When those developers accidently use your library instead of ours, and have problems with it, they not only turn to us with erroneous support incidents, but they also get a bad opinion of the library, which can spill over into social media.

Essentially what you are doing is trademark infringement.  Please stop.  Rename your library to something else.  Thanks.

**Comment by juukie** [comment]
Agree 100% with @mj1856, please rename.

**Comment by spencermountain** [comment]
i agree, @vvpvvp moment.js is a really nice open-source project. It would be respectful to observe this request. 
thanks,

**Comment by mattjohnsonpint** [comment]
Prime example:
http://stackoverflow.com/questions/40147500/incorrect-momentjs-formatting-output-using-examples-from-their-main-page

**Comment by mattjohnsonpint** [comment]
We have resolved the issue with npm.  Please consider renaming your library also.  Thanks.
